### ISSUE TITLE
Allow using redis.StrictRedis instead of hardcoding redis.Redis

### ISSUE THREAD

**Issue by wbolster** [underyx/flask-redis#11]
The summary says it all.

**Comment by rhyselsmore** [comment]
Check the referenced PR @wbolster, let me know if you would prefer this option (where you specify your own redis class), or if you want a 'STRICT" key available to set the strict client.

**Comment by wbolster** [comment]
Hi @rhyselsmore, thanks for working on this.

`redis-py` only provides two classes, and one of them (the one used currently by `Flask-Redis`) only exists for compatibility reasons. My opinion is that a `strict=True` argument is a better approach here. It's cleaner, since it's just a simple self-explanatory toggle, and also because it doesn't "leak" API from the underlying `redis-py` library. With the current implementation in PR#13, consuming applications have to import both `Flask-Redis` *and* `redis` itself to use the (recommended) strict API, which I think is rather ugly.

Fwiw, the default can be left as `strict=False` for backwards compatibility.

**Comment by slick666** [comment]
+1 for this. Wanted to use this with flask-kvsession which requires Strict Redis and had to reference the pull request to get it done.

**Comment by nickw444** [comment]
+1 for this also, would allow publish to be used.

**Comment by slick666** [comment]
w00t!
