### ISSUE TITLE
Default value in `get` when None doesn't work

### ISSUE THREAD

**Issue by mr2uang** [underyx/flask-redis#33]
```
In [11]: with app.app_context():
    ...:     print redis_store.get('quang', 'NO')
    ...:     redis_store.delete('quang')
    ...: 
    ...: 
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-63816f000317> in <module>()
      1 with app.app_context():
----> 2     print redis_store.get('quang', 'NO')
      3     redis_store.delete('quang')
      4
      5

TypeError: get() takes exactly 2 arguments (3 given)

```
In your code does it provide default value?

**Comment by underyx** [comment]
Hey @mr2uang!

I think this issue is not caused by my code. If you look at (the underlying) [redis-py package's documentation](https://redis-py.readthedocs.io/en/latest/#redis.StrictRedis.get) it doesn't support default values for `GET` commands.

I would suggest handling it manually afterwards:

```python
result = redis_store.get('quang')
if result is None:
    result = 'NO'
```

**Comment by mr2uang** [comment]
@underyx Hmm I know `redis` doesn't support it but your Docs in Usage part
```
from core import redis_store

@app.route('/')
def index():
    return redis_store.get('potato', 'Not Set')
```
I thought you add it in `flask_redis`

**Comment by underyx** [comment]
It seems that the documentation is incorrect, then. Would you like to have
a go at submitting a pull request to fix it?
